# Minimal network configuration

include = ["net.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256

# Package settings
[packages]
ca-certificates = {}
extrautils = {}
findutils = {}
ion = {}
netdb = {}
pkgutils = {}
smith = {}
userutils = {}

[[files]]
path = "/usr/lib/init.d/30_console"
data = """
inputd -A 2
getty 2
getty /scheme/debug -J
"""

[[files]]
path = "/etc/pkg.d/50_redox"
data = "https://static.redox-os.org/pkg"
